import 'package:bimobondapp/app/ar_camera/ar_color_filter_catalog_model.dart';

/// Offline filter seed (no LUT PNGs) — Instagram-style color grades, built on
/// the same color-grade engine as the Face retouch sliders
/// (ArCameraBridge.setRetouchAdjustments), already proven stable, plus the
/// baseline skin-smooth beauty effect on top. Values deliberately stronger
/// than a subtle grade so each filter reads as a clearly different look.
///
/// Grouped into categories matching the backend's `colorFilterCategories`
/// shape (same category ids as GET /camera-studio/color-filters), so the
/// offline fallback looks the same as the dynamic catalog when the network
/// call fails — see ar_color_filter_remote_loader.dart.
///
/// Dynamic source: GET /camera-studio/color-filters
/// Fallback: [ArFilterCatalog.restoreBundledColorCatalog]
class ArColorFilterBundledCatalog {
  ArColorFilterBundledCatalog._();

  static const ArColorFilterCatalog catalog = ArColorFilterCatalog(
    version: 'bundled-17',
    categories: [
      ArColorFilterCategoryModel(
        id: 'portrait',
        label: 'Portrait',
        sortOrder: 0,
        filters: [
          ArColorFilterItemModel(
            id: 'normal',
            label: 'Normal',
            emoji: '⚪',
            sortOrder: 0,
            previewColorHex: '#FFFFFF',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
            ),
          ),
          ArColorFilterItemModel(
            id: 'bright',
            label: 'Bright',
            emoji: '☀️',
            sortOrder: 1,
            previewColorHex: '#FFF4D6',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              brightness: 0.35,
              contrast: 0.10,
              saturation: 0.10,
            ),
          ),
          ArColorFilterItemModel(
            id: 'soft_pastel',
            label: 'Soft Pastel',
            emoji: '🌸',
            sortOrder: 2,
            previewColorHex: '#F7E0EC',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              brightness: 0.20,
              contrast: -0.25,
              saturation: -0.30,
              warmth: 0.10,
            ),
          ),
        ],
      ),
      ArColorFilterCategoryModel(
        id: 'trending',
        label: 'Trending',
        sortOrder: 1,
        filters: [
          ArColorFilterItemModel(
            id: 'vivid',
            label: 'Vivid',
            emoji: '🌈',
            sortOrder: 0,
            previewColorHex: '#FF6B9D',
            params: ArBeautyFilterParams(
              smooth: 2,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              brightness: 0.10,
              contrast: 0.25,
              saturation: 0.40,
            ),
          ),
          ArColorFilterItemModel(
            id: 'high_contrast',
            label: 'High Contrast',
            emoji: '⚡',
            sortOrder: 1,
            previewColorHex: '#1A1A1A',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              contrast: 0.45,
              saturation: 0.15,
            ),
          ),
          ArColorFilterItemModel(
            id: 'warm_glow',
            label: 'Warm Glow',
            emoji: '🔥',
            sortOrder: 2,
            previewColorHex: '#FFB570',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              brightness: 0.15,
              contrast: 0.05,
              saturation: 0.15,
              warmth: 0.35,
            ),
          ),
        ],
      ),
      ArColorFilterCategoryModel(
        id: 'life',
        label: 'Life',
        sortOrder: 2,
        filters: [
          ArColorFilterItemModel(
            id: 'fade',
            label: 'Fade',
            emoji: '🌫️',
            sortOrder: 0,
            previewColorHex: '#E8DFD6',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              brightness: 0.10,
              contrast: -0.10,
              saturation: -0.20,
            ),
          ),
          ArColorFilterItemModel(
            id: 'fade_warm',
            label: 'Fade Warm',
            emoji: '🌅',
            sortOrder: 1,
            previewColorHex: '#F0DCC4',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              brightness: 0.10,
              contrast: -0.10,
              saturation: -0.20,
              warmth: 0.20,
            ),
          ),
          ArColorFilterItemModel(
            id: 'fade_cool',
            label: 'Fade Cool',
            emoji: '❄️',
            sortOrder: 2,
            previewColorHex: '#DCE6EC',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              brightness: 0.10,
              contrast: -0.10,
              saturation: -0.20,
              warmth: -0.20,
            ),
          ),
        ],
      ),
      ArColorFilterCategoryModel(
        id: 'retro',
        label: 'Retro',
        sortOrder: 3,
        filters: [
          ArColorFilterItemModel(
            id: 'vintage',
            label: 'Vintage',
            emoji: '📻',
            sortOrder: 0,
            previewColorHex: '#C9A876',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              brightness: 0.05,
              contrast: -0.15,
              saturation: -0.35,
              warmth: 0.30,
            ),
          ),
          ArColorFilterItemModel(
            id: 'noir',
            label: 'Noir',
            emoji: '🎬',
            sortOrder: 1,
            previewColorHex: '#2B2B2B',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              brightness: -0.10,
              contrast: 0.35,
              saturation: -1.0,
            ),
          ),
          ArColorFilterItemModel(
            id: 'black_white',
            label: 'Black & White',
            emoji: '⚫',
            sortOrder: 2,
            previewColorHex: '#808080',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              contrast: 0.15,
              saturation: -1.0,
            ),
          ),
        ],
      ),
      ArColorFilterCategoryModel(
        id: 'film',
        label: 'Film',
        sortOrder: 4,
        filters: [
          ArColorFilterItemModel(
            id: 'moody',
            label: 'Moody',
            emoji: '🌑',
            sortOrder: 0,
            previewColorHex: '#3A3A42',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              brightness: -0.15,
              contrast: 0.30,
              saturation: -0.25,
              warmth: -0.10,
            ),
          ),
          ArColorFilterItemModel(
            id: 'golden_hour',
            label: 'Golden Hour',
            emoji: '🌇',
            sortOrder: 1,
            previewColorHex: '#F5A623',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              brightness: 0.20,
              contrast: 0.10,
              saturation: 0.20,
              warmth: 0.45,
            ),
          ),
          ArColorFilterItemModel(
            id: 'cool_tone',
            label: 'Cool Tone',
            emoji: '🧊',
            sortOrder: 2,
            previewColorHex: '#A8C8E8',
            params: ArBeautyFilterParams(
              smooth: 0.55,
              whiten: 0,
              brighten: 0,
              blush: 0,
              lipTint: '#E8527A',
              lipStrength: 0,
              brightness: 0.05,
              contrast: 0.10,
              saturation: 0.05,
              warmth: -0.35,
            ),
          ),
        ],
      ),
    ],
  );
}
