import 'package:bimobondapp/app/ar_camera/ar_color_filter_catalog_model.dart';

/// App-only offline color-filter seed (not for backend handoff).
/// LUT PNGs live in assets/luts/. Replaced at runtime when the API responds.
class ArColorFilterBundledCatalog {
  ArColorFilterBundledCatalog._();

  static const ArColorFilterCatalog catalog = ArColorFilterCatalog(
    version: 'bundled',
    categories: [
      ArColorFilterCategoryModel(
        id: 'portrait',
        label: 'Portrait',
        sortOrder: 0,
        filters: [
          ArColorFilterItemModel(
            id: 'whitening',
            label: 'Pure',
            emoji: '🤍',
            sortOrder: 0,
            previewColorHex: '#F0E0D0',
            lutAsset: 'whitening.png',
          ),
          ArColorFilterItemModel(
            id: 'clarendon',
            label: 'Bright',
            emoji: '☀️',
            sortOrder: 1,
            previewColorHex: '#FFF3D6',
            lutAsset: 'clarendon.png',
          ),
          ArColorFilterItemModel(
            id: 'ludwig',
            label: 'Clean',
            emoji: '✨',
            sortOrder: 2,
            previewColorHex: '#EAF2F5',
            lutAsset: 'ludwig.png',
          ),
          ArColorFilterItemModel(
            id: 'rosy',
            label: 'Soft',
            emoji: '🌸',
            sortOrder: 3,
            previewColorHex: '#F9DCE0',
            lutAsset: 'rosy.png',
          ),
          ArColorFilterItemModel(
            id: 'valencia',
            label: 'Sunset',
            emoji: '🌇',
            sortOrder: 4,
            previewColorHex: '#F7C9A3',
            lutAsset: 'valencia.png',
          ),
        ],
      ),
      ArColorFilterCategoryModel(
        id: 'life',
        label: 'Life',
        sortOrder: 1,
        filters: [
          ArColorFilterItemModel(
            id: 'warm',
            label: 'Warm',
            emoji: '🍑',
            sortOrder: 0,
            previewColorHex: '#F6C6A0',
            lutAsset: 'warm.png',
          ),
          ArColorFilterItemModel(
            id: 'cool',
            label: 'Cool',
            emoji: '❄️',
            sortOrder: 1,
            previewColorHex: '#BFE0F2',
            lutAsset: 'cool.png',
          ),
        ],
      ),
      ArColorFilterCategoryModel(
        id: 'retro',
        label: 'Retro',
        sortOrder: 2,
        filters: [
          ArColorFilterItemModel(
            id: 'vintage',
            label: 'Retro',
            emoji: '🎞️',
            sortOrder: 0,
            previewColorHex: '#D8C39A',
            lutAsset: 'vintage.png',
          ),
          ArColorFilterItemModel(
            id: 'mono',
            label: 'B & W',
            emoji: '🖤',
            sortOrder: 1,
            previewColorHex: '#B0B0B0',
            lutAsset: 'mono.png',
          ),
          ArColorFilterItemModel(
            id: 'cityfilm',
            label: 'City Film',
            emoji: '🎬',
            sortOrder: 2,
            previewColorHex: '#9AA7B0',
            lutAsset: 'cityfilm.png',
          ),
        ],
      ),
      ArColorFilterCategoryModel(
        id: 'film',
        label: 'Film',
        sortOrder: 3,
        filters: [
          ArColorFilterItemModel(
            id: 'going_for_a_walk',
            label: 'Going for a Walk',
            emoji: '🚶',
            sortOrder: 0,
            previewColorHex: '#A8B89A',
            lutAsset: 'going_for_a_walk.png',
          ),
          ArColorFilterItemModel(
            id: 'good_morning',
            label: 'Good Morning',
            emoji: '🌅',
            sortOrder: 1,
            previewColorHex: '#F3D9A6',
            lutAsset: 'good_morning.png',
          ),
          ArColorFilterItemModel(
            id: 'nah',
            label: 'Nah',
            emoji: '😎',
            sortOrder: 2,
            previewColorHex: '#B6ADA0',
            lutAsset: 'nah.png',
          ),
          ArColorFilterItemModel(
            id: 'once_upon_a_time',
            label: 'Once Upon a Time',
            emoji: '📖',
            sortOrder: 3,
            previewColorHex: '#C9B08A',
            lutAsset: 'once_upon_a_time.png',
          ),
          ArColorFilterItemModel(
            id: 'passing_by',
            label: 'Passing By',
            emoji: '🚗',
            sortOrder: 4,
            previewColorHex: '#9FB0B5',
            lutAsset: 'passing_by.png',
          ),
          ArColorFilterItemModel(
            id: 'serenity',
            label: 'Serenity',
            emoji: '🕊️',
            sortOrder: 5,
            previewColorHex: '#Bcd3d6',
            lutAsset: 'serenity.png',
          ),
          ArColorFilterItemModel(
            id: 'undeniable_2',
            label: 'Undeniable 2',
            emoji: '✨',
            sortOrder: 6,
            previewColorHex: '#D2B7A0',
            lutAsset: 'undeniable_2.png',
          ),
          ArColorFilterItemModel(
            id: 'undeniable',
            label: 'Undeniable',
            emoji: '💫',
            sortOrder: 7,
            previewColorHex: '#D2B7A0',
            lutAsset: 'undeniable.png',
          ),
          ArColorFilterItemModel(
            id: 'urban_cowboy',
            label: 'Urban Cowboy',
            emoji: '🤠',
            sortOrder: 8,
            previewColorHex: '#C7A98A',
            lutAsset: 'urban_cowboy.png',
          ),
          ArColorFilterItemModel(
            id: 'you_can_do_it',
            label: 'You Can Do It',
            emoji: '💪',
            sortOrder: 9,
            previewColorHex: '#E0C6A6',
            lutAsset: 'you_can_do_it.png',
          ),
          ArColorFilterItemModel(
            id: 'smooth_sailing',
            label: 'Smooth Sailing',
            emoji: '⛵',
            sortOrder: 10,
            previewColorHex: '#A9C4CC',
            lutAsset: 'smooth_sailing.png',
          ),
          ArColorFilterItemModel(
            id: 'well_see',
            label: "We'll See",
            emoji: '🌤️',
            sortOrder: 11,
            previewColorHex: '#C3C0B2',
            lutAsset: 'well_see.png',
          ),
        ],
      ),
    ],
  );
}
